/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBaseCard: typeof import('./src/components/AppBaseCard.vue')['default']
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    AppSwitchTheme: typeof import('./src/components/AppSwitchTheme.vue')['default']
    IconMdiBellAlertOutline: typeof import('~icons/mdi/bell-alert-outline')['default']
    IconMdiCheckboxMarkedCirclePlusOutline: typeof import('~icons/mdi/checkbox-marked-circle-plus-outline')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiCircle: typeof import('~icons/mdi/circle')['default']
    IconMdiHome: typeof import('~icons/mdi/home')['default']
    IconMdiImageBrokenVariant: typeof import('~icons/mdi/image-broken-variant')['default']
    IconMdiLogout: typeof import('~icons/mdi/logout')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiPaletteSwatchOutline: typeof import('~icons/mdi/palette-swatch-outline')['default']
    IconSet: typeof import('./src/components/app-drawer-partials/IconSet.vue')['default']
    LogoNav: typeof import('./src/components/app-drawer-partials/LogoNav.vue')['default']
    NavCollapse: typeof import('./src/components/app-drawer-partials/NavCollapse.vue')['default']
    NavGroup: typeof import('./src/components/app-drawer-partials/NavGroup.vue')['default']
    NavItem: typeof import('./src/components/app-drawer-partials/NavItem.vue')['default']
    NotificationExpand: typeof import('./src/components/app-bar-partials/NotificationExpand.vue')['default']
    ProfileExpand: typeof import('./src/components/app-bar-partials/ProfileExpand.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAppBar: typeof import('./src/components/TheAppBar.vue')['default']
    TheAppDrawer: typeof import('./src/components/TheAppDrawer.vue')['default']
    TheAppErrorCard: typeof import('./src/components/TheAppErrorCard.vue')['default']
    TheAppFooter: typeof import('./src/components/TheAppFooter.vue')['default']
  }
}
